parameters:
  - name: BuildPool
    type: string
    default: 'ubuntu-latest'
  - name: AzureArmServiceConnection
    type: string
    default: test0407-2
  - name: TerraformDirectory
    type: string
    default: $(Build.SourcesDirectory)/dev

variables:
  - name: System.Debug
    value: true

stages:
  - stage: Build_TFPlan
    jobs:
      - job: Build_TFPlan
        pool: 
          vmImage: ${{ parameters.BuildPool }}
        steps:
          # Get secrets to use with terraform init
          # The variables referenced here are set by the az cli task, and derived from the service connection provided to the azureSubscription input.
          - task: AzureCLI@2
            name: Terraform_Credentials
            inputs:
              addSpnToEnvironment: true
              azureSubscription: ${{ parameters.AzureArmServiceConnection }}
              scriptType: pscore
              scriptLocation: inlineScript
              inlineScript: |
                Write-Host 'Dump Env vars'
                Get-ChildItem Env:
                Write-Host "##vso[task.setvariable variable=ARM_CLIENT_ID;issecret=true]$($env:servicePrincipalId)"
                Write-Host "##vso[task.setvariable variable=ARM_OIDC_TOKEN;issecret=true]$($env:idToken)"
                Write-Host "##vso[task.setvariable variable=ARM_TENANT_ID;issecret=true]$($env:tenantId)"
                Write-Host "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID;issecret=true]$(az account show --query id -o tsv)"
                Write-Host "##vso[task.setvariable variable=ARM_USE_OIDC]true"
          - task: AzureCLI@2
            name: Terraform_Init
            env:
              ARM_CLIENT_ID: $(ARM_CLIENT_ID)
              ARM_OIDC_TOKEN: $(ARM_OIDC_TOKEN)
              ARM_TENANT_ID: $(ARM_TENANT_ID)
              ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
              ARM_USE_OIDC: $(ARM_USE_OIDC)
            inputs:
              addSpnToEnvironment: true
              azureSubscription: ${{ parameters.AzureArmServiceConnection }}
              scriptType: pscore
              scriptLocation: inlineScript
              workingDirectory: ${{ parameters.TerraformDirectory }}
              inlineScript: |
                terraform init
          # - task: PowerShell@2
          #   name: Terraform_Init
          #   env:
          #     ARM_CLIENT_ID: $(ARM_CLIENT_ID)
          #     ARM_OIDC_TOKEN: $(ARM_OIDC_TOKEN)
          #     ARM_TENANT_ID: $(ARM_TENANT_ID)
          #     ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
          #     ARM_USE_OIDC: $(ARM_USE_OIDC)
          #   inputs:
          #     pwsh: true
          #     targetType : inline
          #     workingDirectory: ${{ parameters.TerraformDirectory }}
          #     script: |
          #       terraform init
          - task: PowerShell@2
            name: Terraform_Plan
            
            inputs:
              pwsh: true
              targetType: inline
              workingDirectory: ${{ parameters.TerraformDirectory }}
              script: |
                terraform plan

                

              
